dockerenvdemo:
  dockerfile: Dockerfile.debug
  build: .
  ports:
    - "${DOCKERENVDEMO_PORT}:${DOCKERENVDEMO_PORT}"
  environment:
    - SERVER.URLS=http://*:${DOCKERENVDEMO_PORT}
    - Hosting:Environment=Development
  volumes:
    - ${DOCKERENVDEMO_PATH}:/app
  env_file: envDevelopment.list