dockerenvdemo:
  container_name: dockerdemo_release
  dockerfile: Dockerfile.release
  build: .
  ports:
    - "${DOCKERENVDEMO_PORT}:${DOCKERENVDEMO_PORT}"
  env_file: envDevelopment.list
  environment:
    - SERVER.URLS=http://*:${DOCKERENVDEMO_PORT}
    - Hosting:Environment=Production

