dockerenvdemo:
  build: ..
  dockerfile: Docker/Dockerfile.debug
  ports:
    - "${DOCKERENVDEMO_PORT}:${DOCKERENVDEMO_PORT}"
  environment:
    - SERVER.URLS=http://*:${DOCKERENVDEMO_PORT}
  volumes:
    - ..:/app
